#include "strace.h"
#include <errno.h>

t_errno errnoTable[] = {
		[1] = { .nb = 1, .code = "EPERM", .description = "Operation not permitted" },
		[2] = { .nb = 2, .code = "ENOENT", .description = "No such file or directory" },
		[3] = { .nb = 3, .code = "ESRCH", .description = "No such process" },
		[4] = { .nb = 4, .code = "EINTR", .description = "Interrupted system call" },
		[5] = { .nb = 5, .code = "EIO", .description = "I/O error" },
		[6] = { .nb = 6, .code = "ENXIO", .description = "No such device or address" },
		[7] = { .nb = 7, .code = "E2BIG", .description = "Argument list too long" },
		[8] = { .nb = 8, .code = "ENOEXEC", .description = "Exec format error" },
		[9] = { .nb = 9, .code = "EBADF", .description = "Bad file number" },
		[10] = { .nb = 10, .code = "ECHILD", .description = "No child processes" },
		[11] = { .nb = 11, .code = "EAGAIN", .description = "Try again" },
		[12] = { .nb = 12, .code = "ENOMEM", .description = "Out of memory" },
		[13] = { .nb = 13, .code = "EACCES", .description = "Permission denied" },
		[14] = { .nb = 14, .code = "EFAULT", .description = "Bad address" },
		[15] = { .nb = 15, .code = "ENOTBLK", .description = "Block device required" },
		[16] = { .nb = 16, .code = "EBUSY", .description = "Device or resource busy" },
		[17] = { .nb = 17, .code = "EEXIST", .description = "File exists" },
		[18] = { .nb = 18, .code = "EXDEV", .description = "Cross-device link" },
		[19] = { .nb = 19, .code = "ENODEV", .description = "No such device" },
		[20] = { .nb = 20, .code = "ENOTDIR", .description = "Not a directory" },
		[21] = { .nb = 21, .code = "EISDIR", .description = "Is a directory" },
		[22] = { .nb = 22, .code = "EINVAL", .description = "Invalid argument" },
		[23] = { .nb = 23, .code = "ENFILE", .description = "File table overflow" },
		[24] = { .nb = 24, .code = "EMFILE", .description = "Too many open files" },
		[25] = { .nb = 25, .code = "ENOTTY", .description = "Not a typewriter" },
		[26] = { .nb = 26, .code = "ETXTBSY", .description = "Text file busy" },
		[27] = { .nb = 27, .code = "EFBIG", .description = "File too large" },
		[28] = { .nb = 28, .code = "ENOSPC", .description = "No space left on device" },
		[29] = { .nb = 29, .code = "ESPIPE", .description = "Illegal seek" },
		[30] = { .nb = 30, .code = "EROFS", .description = "Read-only file system" },
		[31] = { .nb = 31, .code = "EMLINK", .description = "Too many links" },
		[32] = { .nb = 32, .code = "EPIPE", .description = "Broken pipe" },
		[33] = { .nb = 33, .code = "EDOM", .description = "Math argument out of domain of func" },
		[34] = { .nb = 34, .code = "ERANGE", .description = "Math result not representable" },
		[35] = { .nb = 35, .code = "EDEADLK", .description = "Resource deadlock would occur" },
		[36] = { .nb = 36, .code = "ENAMETOOLONG", .description = "File name too long" },
		[37] = { .nb = 37, .code = "ENOLCK", .description = "No record locks available" },
		[38] = { .nb = 38, .code = "ENOSYS", .description = "Function not implemented" },
		[39] = { .nb = 39, .code = "ENOTEMPTY", .description = "Directory not empty" },
		[40] = { .nb = 40, .code = "ELOOP", .description = "Too many symbolic links encountered" },
		[42] = { .nb = 42, .code = "ENOMSG", .description = "No message of desired type" },
		[43] = { .nb = 43, .code = "EIDRM", .description = "Identifier removed" },
		[44] = { .nb = 44, .code = "ECHRNG", .description = "Channel number out of range" },
		[45] = { .nb = 45, .code = "EL2NSYNC", .description = "Level 2 not synchronized" },
		[46] = { .nb = 46, .code = "EL3HLT", .description = "Level 3 halted" },
		[47] = { .nb = 47, .code = "EL3RST", .description = "Level 3 reset" },
		[48] = { .nb = 48, .code = "ELNRNG", .description = "Link number out of range" },
		[49] = { .nb = 49, .code = "EUNATCH", .description = "Protocol driver not attached" },
		[50] = { .nb = 50, .code = "ENOCSI", .description = "No CSI structure available" },
		[51] = { .nb = 51, .code = "EL2HLT", .description = "Level 2 halted" },
		[52] = { .nb = 52, .code = "EBADE", .description = "Invalid exchange" },
		[53] = { .nb = 53, .code = "EBADR", .description = "Invalid request descriptor" },
		[54] = { .nb = 54, .code = "EXFULL", .description = "Exchange full" },
		[55] = { .nb = 55, .code = "ENOANO", .description = "No anode" },
		[56] = { .nb = 56, .code = "EBADRQC", .description = "Invalid request code" },
		[57] = { .nb = 57, .code = "EBADSLT", .description = "Invalid slot" },
		[59] = { .nb = 59, .code = "EBFONT", .description = "Bad font file format" },
		[60] = { .nb = 60, .code = "ENOSTR", .description = "Device not a stream" },
		[61] = { .nb = 61, .code = "ENODATA", .description = "No data available" },
		[62] = { .nb = 62, .code = "ETIME", .description = "Timer expired" },
		[63] = { .nb = 63, .code = "ENOSR", .description = "Out of streams resources" },
		[64] = { .nb = 64, .code = "ENONET", .description = "Machine is not on the network" },
		[65] = { .nb = 65, .code = "ENOPKG", .description = "Package not installed" },
		[66] = { .nb = 66, .code = "EREMOTE", .description = "Object is remote" },
		[67] = { .nb = 67, .code = "ENOLINK", .description = "Link has been severed" },
		[68] = { .nb = 68, .code = "EADV", .description = "Advertise error" },
		[69] = { .nb = 69, .code = "ESRMNT", .description = "Srmount error" },
		[70] = { .nb = 70, .code = "ECOMM", .description = "Communication error on send" },
		[71] = { .nb = 71, .code = "EPROTO", .description = "Protocol error" },
		[72] = { .nb = 72, .code = "EMULTIHOP", .description = "Multihop attempted" },
		[73] = { .nb = 73, .code = "EDOTDOT", .description = "RFS specific error" },
		[74] = { .nb = 74, .code = "EBADMSG", .description = "Not a data message" },
		[75] = { .nb = 75, .code = "EOVERFLOW", .description = "Value too large for defined data type" },
		[76] = { .nb = 76, .code = "ENOTUNIQ", .description = "Name not unique on network" },
		[77] = { .nb = 77, .code = "EBADFD", .description = "File descriptor in bad state" },
		[78] = { .nb = 78, .code = "EREMCHG", .description = "Remote address changed" },
		[79] = { .nb = 79, .code = "ELIBACC", .description = "Can not access a needed shared library" },
		[80] = { .nb = 80, .code = "ELIBBAD", .description = "Accessing a corrupted shared library" },
		[81] = { .nb = 81, .code = "ELIBSCN", .description = ".lib section in a.out corrupted" },
		[82] = { .nb = 82, .code = "ELIBMAX", .description = "Attempting to link in too many shared libraries" },
		[83] = { .nb = 83, .code = "ELIBEXEC", .description = "Cannot exec a shared library directly" },
		[84] = { .nb = 84, .code = "EILSEQ", .description = "Illegal byte sequence" },
		[85] = { .nb = 85, .code = "ERESTART", .description = "Interrupted system call should be restarted" },
		[86] = { .nb = 86, .code = "ESTRPIPE", .description = "Streams pipe error" },
		[87] = { .nb = 87, .code = "EUSERS", .description = "Too many users" },
		[88] = { .nb = 88, .code = "ENOTSOCK", .description = "Socket operation on non-socket" },
		[89] = { .nb = 89, .code = "EDESTADDRREQ", .description = "Destination address required" },
		[90] = { .nb = 90, .code = "EMSGSIZE", .description = "Message too long" },
		[91] = { .nb = 91, .code = "EPROTOTYPE", .description = "Protocol wrong type for socket" },
		[92] = { .nb = 92, .code = "ENOPROTOOPT", .description = "Protocol not available" },
		[93] = { .nb = 93, .code = "EPROTONOSUPPORT", .description = "Protocol not supported" },
		[94] = { .nb = 94, .code = "ESOCKTNOSUPPORT", .description = "Socket type not supported" },
		[95] = { .nb = 95, .code = "EOPNOTSUPP", .description = "Operation not supported on transport endpoint" },
		[96] = { .nb = 96, .code = "EPFNOSUPPORT", .description = "Protocol family not supported" },
		[97] = { .nb = 97, .code = "EAFNOSUPPORT", .description = "Address family not supported by protocol" },
		[98] = { .nb = 98, .code = "EADDRINUSE", .description = "Address already in use" },
		[99] = { .nb = 99, .code = "EADDRNOTAVAIL", .description = "Cannot assign requested address" },
		[100] = { .nb = 100, .code = "ENETDOWN", .description = "Network is down" },
		[101] = { .nb = 101, .code = "ENETUNREACH", .description = "Network is unreachable" },
		[102] = { .nb = 102, .code = "ENETRESET", .description = "Network dropped connection because of reset" },
		[103] = { .nb = 103, .code = "ECONNABORTED", .description = "Software caused connection abort" },
		[104] = { .nb = 104, .code = "ECONNRESET", .description = "Connection reset by peer" },
		[105] = { .nb = 105, .code = "ENOBUFS", .description = "No buffer space available" },
		[106] = { .nb = 106, .code = "EISCONN", .description = "Transport endpoint is already connected" },
		[107] = { .nb = 107, .code = "ENOTCONN", .description = "Transport endpoint is not connected" },
		[108] = { .nb = 108, .code = "ESHUTDOWN", .description = "Cannot send after transport endpoint shutdown" },
		[109] = { .nb = 109, .code = "ETOOMANYREFS", .description = "Too many references: cannot splice" },
		[110] = { .nb = 110, .code = "ETIMEDOUT", .description = "Connection timed out" },
		[111] = { .nb = 111, .code = "ECONNREFUSED", .description = "Connection refused" },
		[112] = { .nb = 112, .code = "EHOSTDOWN", .description = "Host is down" },
		[113] = { .nb = 113, .code = "EHOSTUNREACH", .description = "No route to host" },
		[114] = { .nb = 114, .code = "EALREADY", .description = "Operation already in progress" },
		[115] = { .nb = 115, .code = "EINPROGRESS", .description = "Operation now in progress" },
		[116] = { .nb = 116, .code = "ESTALE", .description = "Stale NFS file handle" },
		[117] = { .nb = 117, .code = "EUCLEAN", .description = "Structure needs cleaning" },
		[118] = { .nb = 118, .code = "ENOTNAM", .description = "Not a XENIX named type file" },
		[119] = { .nb = 119, .code = "ENAVAIL", .description = "No XENIX semaphores available" },
		[120] = { .nb = 120, .code = "EISNAM", .description = "Is a named type file" },
		[121] = { .nb = 121, .code = "EREMOTEIO", .description = "Remote I/O error" },
		[122] = { .nb = 122, .code = "EDQUOT", .description = "Quota exceeded" },
		[123] = { .nb = 123, .code = "ENOMEDIUM", .description = "No medium found" },
		[124] = { .nb = 124, .code = "EMEDIUMTYPE", .description = "Wrong medium type" },
		[125] = { .nb = 125, .code = "ECANCELED", .description = "Operation Canceled" },
		[126] = { .nb = 126, .code = "ENOKEY", .description = "Required key not available" },
		[127] = { .nb = 127, .code = "EKEYEXPIRED", .description = "Key has expired" },
		[128] = { .nb = 128, .code = "EKEYREVOKED", .description = "Key has been revoked" },
		[129] = { .nb = 129, .code = "EKEYREJECTED", .description = "Key was rejected by service" },
		[130] = { .nb = 130, .code = "EOWNERDEAD", .description = "Owner died" },
		[131] = { .nb = 131, .code = "ENOTRECOVERABLE", .description = "State not recoverable" },
};

