//
// Created by Peer de Bakker on 6/20/22.
//

#include "syscalls.h"

#define MAX_SYSCALL_NB 60

t_syscall syscalls[] = {
		{.nb64 = 0, .nb32 = 3, .return_value = SSIZE_T, .name = "read",      INT,          VOID_POINTER, SIZE_T,  NONE,    NONE, NONE},
		{.nb64 = 1, .nb32 = 4, .return_value = SSIZE_T, .name = "write",     INT,          VOID_POINTER, SIZE_T,  NONE,    NONE, NONE},
		{.nb64 = 2, .nb32 = 5, .return_value = INT, .name = "open",          STRING,       INT,          NONE,    NONE,    NONE, NONE},
		{.nb64 = 3, .nb32 = 6, .return_value = INT, .name = "close",         INT,          NONE,         NONE,    NONE,    NONE, NONE},
		{.nb64 = 4, .nb32 = 106, .return_value = INT, .name = "stat",          STRING,       POINTER,      NONE,    NONE,    NONE, NONE},
		{.nb64 = 5, .nb32 = 108, .return_value = INT, .name = "fstat",         INT,          POINTER,      NONE,    NONE,    NONE, NONE},
		{.nb64 = 6, .nb32 = 107, .return_value = INT, .name = "lstat",         STRING,       POINTER,      NONE,    NONE,    NONE, NONE},
		{.nb64 = 7, .nb32 = 168, .return_value = INT, .name = "poll",          POINTER,      STRUCT,       POINTER, POINTER, NONE, NONE},
		{.nb64 = 8, .nb32 = 19, .return_value = INT, .name = "lseek",         INT,          INT,          INT,     NONE,    NONE, NONE},
		{.nb64 = 9, .nb32 = 90, .return_value = VOID_POINTER, .name = "mmap", VOID_POINTER, SIZE_T,       INT,     INT,     INT,  INT},
		{.nb64 = 10, .nb32 = 125, .return_value = INT, .name = "mprotect", POINTER, UNSIGNED_INT, UNSIGNED_INT, NONE, NONE, NONE},
		{.nb64 = 11, .nb32 = 91, .return_value = INT, .name = "munmap", POINTER, UNSIGNED_INT, NONE, NONE, NONE, NONE},
		{.nb64 = 12, .nb32 = 45, .return_value = POINTER, .name = "brk", POINTER, NONE, NONE, NONE, NONE, NONE},
		{.nb64 = 13, .nb32 = 174, .return_value = INT, .name = "rt_sigaction", INT, POINTER, POINTER, UNSIGNED_INT, NONE, NONE},
		{.nb64 = 14, .nb32 = 175, .return_value = INT, .name = "rt_sigprocmask", INT, POINTER, POINTER, UNSIGNED_INT, NONE, NONE},
		{.nb64 = 15, .nb32 = 173, .return_value = INT, .name = "rt_sigreturn", UNSIGNED_INT, NONE, NONE, NONE, NONE, NONE},
		{.nb64 = 16, .nb32 = 54, .return_value = INT, .name = "ioctl", UNSIGNED_INT, UNSIGNED_INT, UNSIGNED_INT, NONE, NONE, NONE},
		{.nb64 = 17, .nb32 = 180, .return_value = INT, .name = "pread64", UNSIGNED_INT, VOID_POINTER, UNSIGNED_INT, UNSIGNED_INT, NONE, NONE},
		{.nb64 = 18, .nb32 = 181, .return_value = INT, .name = "pwrite64", UNSIGNED_INT, VOID_POINTER, UNSIGNED_INT, UNSIGNED_INT, NONE, NONE},
		{.nb64 = 19, .nb32 = 145, .return_value = INT, .name = "readv", UNSIGNED_INT, POINTER, UNSIGNED_INT, NONE, NONE, NONE},
		{.nb64 = 20, .nb32 = 146, .return_value = INT, .name = "writev", UNSIGNED_INT, POINTER, UNSIGNED_INT, NONE, NONE, NONE},
		{.nb64 = 21, .nb32 = 33, .return_value = INT, .name = "access", VOID_POINTER, INT, NONE, NONE, NONE, NONE},
		{.nb64 = 22, .nb32 = 42, .return_value = INT, .name = "pipe", POINTER, NONE, NONE, NONE, NONE, NONE},
		{.nb64 = 23, .nb32 = 82, .return_value = INT, .name = "select", INT, POINTER, POINTER, POINTER, POINTER, NONE},
		{.nb64 = 24, .nb32 = 158, .return_value = INT, .name = "sched_yield", NONE, NONE, NONE, NONE, NONE, NONE},
		{.nb64 = 25, .nb32 = 163, .return_value = INT, .name = "mremap", UNSIGNED_INT, UNSIGNED_INT, UNSIGNED_INT, UNSIGNED_INT, UNSIGNED_INT, NONE},
		{.nb64 = 26, .nb32 = 144, .return_value = INT, .name = "msync", UNSIGNED_INT, UNSIGNED_INT, INT, NONE, NONE, NONE},
		{.nb64 = 27, .nb32 = 218, .return_value = INT, .name = "mincore", UNSIGNED_INT, UNSIGNED_INT, VOID_POINTER, NONE, NONE, NONE},
		{.nb64 = 28, .nb32 = 219, .return_value = INT, .name = "madvise", UNSIGNED_INT, UNSIGNED_INT, INT, NONE, NONE, NONE},
		{.nb64 = 29, .nb32 = -1, .return_value = INT, .name = "shmget", INT, UNSIGNED_INT, INT, NONE, NONE, NONE},
		{.nb64 = 30, .nb32 = -1, .return_value = INT, .name = "shmat", INT, VOID_POINTER, INT, NONE, NONE, NONE},
		{.nb64 = 31, .nb32 = -1, .return_value = INT, .name = "shmctl", INT, INT, POINTER, NONE, NONE, NONE},
		{.nb64 = 32, .nb32 = 41, .return_value = INT, .name = "dup", UNSIGNED_INT, NONE, NONE, NONE, NONE, NONE},
		{.nb64 = 33, .nb32 = 63, .return_value = INT, .name = "dup2", UNSIGNED_INT, UNSIGNED_INT, NONE, NONE, NONE, NONE},
		{.nb64 = 34, .nb32 = 29, .return_value = INT, .name = "pause", NONE, NONE, NONE, NONE, NONE, NONE},
		{.nb64 = 35, .nb32 = 162, .return_value = INT, .name = "nanosleep", POINTER, POINTER, NONE, NONE, NONE, NONE},
		{.nb64 = 36, .nb32 = 105, .return_value = INT, .name = "getitimer", INT, POINTER, NONE, NONE, NONE, NONE},
		{.nb64 = 37, .nb32 = 27, .return_value = INT, .name = "alarm", UNSIGNED_INT, NONE, NONE, NONE, NONE, NONE},
		{.nb64 = 38, .nb32 = 104, .return_value = INT, .name = "setitimer", INT, POINTER, POINTER, NONE, NONE, NONE},
		{.nb64 = 39, .nb32 = 20, .return_value = INT, .name = "getpid", NONE, NONE, NONE, NONE, NONE, NONE},
		{.nb64 = 40, .nb32 = 187, .return_value = INT, .name = "sendfile", INT, INT, POINTER, UNSIGNED_INT, NONE, NONE},
		{.nb64 = 41, .nb32 = 359, .return_value = INT, .name = "socket", INT, INT, INT, NONE, NONE, NONE},
		{.nb64 = 42, .nb32 = 362, .return_value = INT, .name = "connect", INT, POINTER, INT, NONE, NONE, NONE},
		{.nb64 = 43, .nb32 = -1, .return_value = INT, .name = "accept", INT, POINTER, POINTER, NONE, NONE, NONE},
		{.nb64 = 44, .nb32 = 369, .return_value = INT, .name = "sendto", INT, POINTER, UNSIGNED_INT, UNSIGNED_INT, POINTER, POINTER},
		{.nb64 = 45, .nb32 = 371, .return_value = INT, .name = "recvfrom", INT, POINTER, UNSIGNED_INT, UNSIGNED_INT, POINTER, POINTER},
		{.nb64 = 46, .nb32 = 370, .return_value = INT, .name = "sendmsg", INT, POINTER, UNSIGNED_INT, NONE, NONE, NONE},
		{.nb64 = 47, .nb32 = 372, .return_value = INT, .name = "recvmsg", INT, POINTER, UNSIGNED_INT, NONE, NONE, NONE},
		{.nb64 = 48, .nb32 = 373, .return_value = INT, .name = "shutdown", INT, INT, NONE, NONE, NONE, NONE},
		{.nb64 = 49, .nb32 = 361, .return_value = INT, .name = "bind", INT, POINTER, POINTER, NONE, NONE, NONE},
		{.nb64 = 50, .nb32 = 363, .return_value = INT, .name = "listen", INT, INT, NONE, NONE, NONE, NONE},
		{.nb64 = 51, .nb32 = 367, .return_value = INT, .name = "getsockname", INT, POINTER, POINTER, NONE, NONE, NONE},
		{.nb64 = 52, .nb32 = 368, .return_value = INT, .name = "getpeername", INT, POINTER, POINTER, NONE, NONE, NONE},
		{.nb64 = 53, .nb32 = 360, .return_value = INT, .name = "socketpair", INT, INT, INT, POINTER, NONE, NONE},
		{.nb64 = 54, .nb32 = 366, .return_value = INT, .name = "setsockopt", INT, INT, INT, VOID_POINTER, INT, NONE},
		{.nb64 = 55, .nb32 = 365, .return_value = INT, .name = "getsockopt", INT, INT, INT, VOID_POINTER, POINTER, NONE},
		{.nb64 = 56, .nb32 = 120, .return_value = INT, .name = "clone", UNSIGNED_INT, UNSIGNED_INT, POINTER, POINTER, NONE, NONE},
		{.nb64 = 57, .nb32 = 2, .return_value = INT, .name = "fork", NONE, NONE, NONE, NONE, NONE, NONE},
		{.nb64 = 58, .nb32 = 190, .return_value = INT, .name = "vfork", NONE, NONE, NONE, NONE, NONE, NONE},
		{.nb64 = 59, .nb32 = 11, .return_value = INT, .name = "execve", VOID_POINTER, STRING_ARRAY, STRING_ARRAY, NONE, NONE, NONE},
		{.nb64 = 60, .nb32 = 1, .return_value = INT, .name = "exit", INT, NONE, NONE, NONE, NONE, NONE},
};
