#include "syscalls.h"

t_syscall syscalls[] = {
		[  0] = { .nb64 =   0, .return_value = T_LINT, .name = "read", T_INT, T_BUFF, T_ULINT, T_NONE, T_NONE, T_NONE },
		[  1] = { .nb64 =   1, .return_value = T_LINT, .name = "write", T_INT, T_BUFF, T_ULINT, T_NONE, T_NONE, T_NONE },
		[  2] = { .nb64 =   2, .return_value = T_INT, .name = "open", T_STR, T_INT, T_UINT, T_NONE, T_NONE, T_NONE },
		[  3] = { .nb64 =   3, .return_value = T_INT, .name = "close", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[  4] = { .nb64 =   4, .return_value = T_INT, .name = "stat", T_STR, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[  5] = { .nb64 =   5, .return_value = T_INT, .name = "fstat", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[  6] = { .nb64 =   6, .return_value = T_INT, .name = "lstat", T_STR, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[  7] = { .nb64 =   7, .return_value = T_INT, .name = "poll", T_ADDR, T_ULINT, T_INT, T_NONE, T_NONE, T_NONE },
		[  8] = { .nb64 =   8, .return_value = T_LINT, .name = "lseek", T_INT, T_LINT, T_INT, T_NONE, T_NONE, T_NONE },
		[  9] = { .nb64 =   9, .return_value = T_ADDR, .name = "mmap", T_ADDR, T_ULINT, T_INT, T_INT, T_INT, T_LINT },
		[ 10] = { .nb64 =  10, .return_value = T_INT, .name = "mprotect", T_ADDR, T_ULINT, T_INT, T_NONE, T_NONE, T_NONE },
		[ 11] = { .nb64 =  11, .return_value = T_INT, .name = "munmap", T_ADDR, T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 12] = { .nb64 =  12, .return_value = T_HEX, .name = "brk", T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 13] = { .nb64 =  13, .return_value = T_INT, .name = "rt_sigaction", T_INT, T_ADDR, T_ADDR, T_ULINT, T_NONE, T_NONE },
		[ 14] = { .nb64 =  14, .return_value = T_INT, .name = "rt_sigprocmask", T_INT, T_ADDR, T_ADDR, T_ULINT, T_NONE, T_NONE },
		[ 15] = { .nb64 =  15, .return_value = T_INT, .name = "rt_sigreturn", T_HEX, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 16] = { .nb64 =  16, .return_value = T_INT, .name = "ioctl", T_INT, T_ULINT, T_HEX, T_NONE, T_NONE, T_NONE },
		[ 17] = { .nb64 =  17, .return_value = T_LINT, .name = "pread", T_INT, T_ADDR, T_ULINT, T_LINT, T_NONE, T_NONE },
		[ 18] = { .nb64 =  18, .return_value = T_LINT, .name = "pwrite", T_INT, T_ADDR, T_ULINT, T_LINT, T_NONE, T_NONE },
		[ 19] = { .nb64 =  19, .return_value = T_LINT, .name = "readv", T_INT, T_ADDR, T_INT, T_NONE, T_NONE, T_NONE },
		[ 20] = { .nb64 =  20, .return_value = T_LINT, .name = "writev", T_INT, T_ADDR, T_INT, T_NONE, T_NONE, T_NONE },
		[ 21] = { .nb64 =  21, .return_value = T_INT, .name = "access", T_STR, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 22] = { .nb64 =  22, .return_value = T_INT, .name = "pipe", T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 23] = { .nb64 =  23, .return_value = T_INT, .name = "select", T_INT, T_ADDR, T_ADDR, T_ADDR, T_ADDR, T_NONE },
		[ 24] = { .nb64 =  24, .return_value = T_INT, .name = "sched_yield", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 25] = { .nb64 =  25, .return_value = T_ADDR, .name = "mremap", T_ADDR, T_ULINT, T_ULINT, T_HEX, T_NONE, T_NONE },
		[ 26] = { .nb64 =  26, .return_value = T_INT, .name = "msync", T_ADDR, T_ULINT, T_INT, T_NONE, T_NONE, T_NONE },
		[ 27] = { .nb64 =  27, .return_value = T_INT, .name = "mincore", T_ADDR, T_ULINT, T_ADDR, T_NONE, T_NONE, T_NONE },
		[ 28] = { .nb64 =  28, .return_value = T_INT, .name = "madvise", T_ADDR, T_ULINT, T_INT, T_NONE, T_NONE, T_NONE },
		[ 29] = { .nb64 =  29, .return_value = T_INT, .name = "shmget", T_UNKNOWN, T_ULINT, T_INT, T_NONE, T_NONE, T_NONE },
		[ 30] = { .nb64 =  30, .return_value = T_ADDR, .name = "shmat", T_INT, T_ADDR, T_INT, T_NONE, T_NONE, T_NONE },
		[ 31] = { .nb64 =  31, .return_value = T_INT, .name = "shmctl", T_INT, T_INT, T_ADDR, T_NONE, T_NONE, T_NONE },
		[ 32] = { .nb64 =  32, .return_value = T_INT, .name = "dup", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 33] = { .nb64 =  33, .return_value = T_INT, .name = "dup2", T_INT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 34] = { .nb64 =  34, .return_value = T_INT, .name = "pause", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 35] = { .nb64 =  35, .return_value = T_INT, .name = "nanosleep", T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 36] = { .nb64 =  36, .return_value = T_INT, .name = "getitimer", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 37] = { .nb64 =  37, .return_value = T_UINT, .name = "alarm", T_UINT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 38] = { .nb64 =  38, .return_value = T_INT, .name = "setitimer", T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[ 39] = { .nb64 =  39, .return_value = T_INT, .name = "getpid", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 40] = { .nb64 =  40, .return_value = T_LINT, .name = "sendfile", T_INT, T_INT, T_ADDR, T_ULINT, T_NONE, T_NONE },
		[ 41] = { .nb64 =  41, .return_value = T_INT, .name = "socket", T_INT, T_INT, T_INT, T_NONE, T_NONE, T_NONE },
		[ 42] = { .nb64 =  42, .return_value = T_INT, .name = "connect", T_INT, T_ADDR, T_UINT, T_NONE, T_NONE, T_NONE },
		[ 43] = { .nb64 =  43, .return_value = T_INT, .name = "accept", T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[ 44] = { .nb64 =  44, .return_value = T_LINT, .name = "sendto", T_INT, T_ADDR, T_ULINT, T_INT, T_ADDR, T_UINT },
		[ 45] = { .nb64 =  45, .return_value = T_LINT, .name = "recvfrom", T_INT, T_ADDR, T_ULINT, T_INT, T_ADDR, T_ADDR },
		[ 46] = { .nb64 =  46, .return_value = T_LINT, .name = "sendmsg", T_INT, T_ADDR, T_INT, T_NONE, T_NONE, T_NONE },
		[ 47] = { .nb64 =  47, .return_value = T_LINT, .name = "recvmsg", T_INT, T_ADDR, T_INT, T_NONE, T_NONE, T_NONE },
		[ 48] = { .nb64 =  48, .return_value = T_INT, .name = "shutdown", T_INT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 49] = { .nb64 =  49, .return_value = T_INT, .name = "bind", T_INT, T_ADDR, T_UINT, T_NONE, T_NONE, T_NONE },
		[ 50] = { .nb64 =  50, .return_value = T_INT, .name = "listen", T_INT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 51] = { .nb64 =  51, .return_value = T_INT, .name = "getsockname", T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[ 52] = { .nb64 =  52, .return_value = T_INT, .name = "getpeername", T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[ 53] = { .nb64 =  53, .return_value = T_INT, .name = "socketpair", T_INT, T_INT, T_INT, T_ADDR, T_NONE, T_NONE },
		[ 54] = { .nb64 =  54, .return_value = T_INT, .name = "setsockopt", T_INT, T_INT, T_INT, T_ADDR, T_UINT, T_NONE },
		[ 55] = { .nb64 =  55, .return_value = T_INT, .name = "getsockopt", T_INT, T_INT, T_INT, T_ADDR, T_ADDR, T_NONE },
		[ 56] = { .nb64 =  56, .return_value = T_INT, .name = "clone", T_ADDR, T_ADDR, T_INT, T_ADDR, T_NONE, T_NONE },
		[ 57] = { .nb64 =  57, .return_value = T_INT, .name = "fork", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 58] = { .nb64 =  58, .return_value = T_INT, .name = "vfork", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 59] = { .nb64 =  59, .return_value = T_INT, .name = "execve", T_STR, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[ 60] = { .nb64 =  60, .return_value = T_NONE, .name = "exit", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 61] = { .nb64 =  61, .return_value = T_INT, .name = "wait4", T_INT, T_ADDR, T_INT, T_ADDR, T_NONE, T_NONE },
		[ 62] = { .nb64 =  62, .return_value = T_INT, .name = "kill", T_INT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 63] = { .nb64 =  63, .return_value = T_INT, .name = "uname", T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 64] = { .nb64 =  64, .return_value = T_INT, .name = "semget", T_UNKNOWN, T_INT, T_INT, T_NONE, T_NONE, T_NONE },
		[ 65] = { .nb64 =  65, .return_value = T_INT, .name = "semop", T_INT, T_ADDR, T_ULINT, T_NONE, T_NONE, T_NONE },
		[ 66] = { .nb64 =  66, .return_value = T_INT, .name = "semctl", T_INT, T_INT, T_INT, T_HEX, T_NONE, T_NONE },
		[ 67] = { .nb64 =  67, .return_value = T_INT, .name = "shmdt", T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 68] = { .nb64 =  68, .return_value = T_INT, .name = "msgget", T_UNKNOWN, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 69] = { .nb64 =  69, .return_value = T_INT, .name = "msgsnd", T_INT, T_ADDR, T_ULINT, T_INT, T_NONE, T_NONE },
		[ 70] = { .nb64 =  70, .return_value = T_LINT, .name = "msgrcv", T_INT, T_ADDR, T_ULINT, T_LINT, T_INT, T_NONE },
		[ 71] = { .nb64 =  71, .return_value = T_INT, .name = "msgctl", T_INT, T_INT, T_ADDR, T_NONE, T_NONE, T_NONE },
		[ 72] = { .nb64 =  72, .return_value = T_INT, .name = "fcntl", T_INT, T_INT, T_HEX, T_NONE, T_NONE, T_NONE },
		[ 73] = { .nb64 =  73, .return_value = T_INT, .name = "flock", T_INT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 74] = { .nb64 =  74, .return_value = T_INT, .name = "fsync", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 75] = { .nb64 =  75, .return_value = T_INT, .name = "fdatasync", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 76] = { .nb64 =  76, .return_value = T_INT, .name = "truncate", T_STR, T_LINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 77] = { .nb64 =  77, .return_value = T_INT, .name = "ftruncate", T_INT, T_LINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 78] = { .nb64 =  78, .return_value = T_INT, .name = "getdents", T_UINT, T_ADDR, T_UINT, T_NONE, T_NONE, T_NONE },
		[ 79] = { .nb64 =  79, .return_value = T_STR, .name = "getcwd", T_STR, T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 80] = { .nb64 =  80, .return_value = T_INT, .name = "chdir", T_STR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 81] = { .nb64 =  81, .return_value = T_INT, .name = "fchdir", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 82] = { .nb64 =  82, .return_value = T_INT, .name = "rename", T_STR, T_STR, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 83] = { .nb64 =  83, .return_value = T_INT, .name = "mkdir", T_STR, T_UINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 84] = { .nb64 =  84, .return_value = T_INT, .name = "rmdir", T_STR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 85] = { .nb64 =  85, .return_value = T_INT, .name = "creat", T_STR, T_UINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 86] = { .nb64 =  86, .return_value = T_INT, .name = "link", T_STR, T_STR, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 87] = { .nb64 =  87, .return_value = T_INT, .name = "unlink", T_STR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 88] = { .nb64 =  88, .return_value = T_INT, .name = "symlink", T_STR, T_STR, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 89] = { .nb64 =  89, .return_value = T_LINT, .name = "readlink", T_STR, T_STR, T_ULINT, T_NONE, T_NONE, T_NONE },
		[ 90] = { .nb64 =  90, .return_value = T_INT, .name = "chmod", T_STR, T_UINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 91] = { .nb64 =  91, .return_value = T_INT, .name = "fchmod", T_INT, T_UINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 92] = { .nb64 =  92, .return_value = T_INT, .name = "chown", T_STR, T_UINT, T_UINT, T_NONE, T_NONE, T_NONE },
		[ 93] = { .nb64 =  93, .return_value = T_INT, .name = "fchown", T_INT, T_UINT, T_UINT, T_NONE, T_NONE, T_NONE },
		[ 94] = { .nb64 =  94, .return_value = T_INT, .name = "lchown", T_STR, T_UINT, T_UINT, T_NONE, T_NONE, T_NONE },
		[ 95] = { .nb64 =  95, .return_value = T_UINT, .name = "umask", T_UINT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 96] = { .nb64 =  96, .return_value = T_INT, .name = "gettimeofday", T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 97] = { .nb64 =  97, .return_value = T_INT, .name = "getrlimit", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 98] = { .nb64 =  98, .return_value = T_INT, .name = "getrusage", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[ 99] = { .nb64 =  99, .return_value = T_INT, .name = "sysinfo", T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[100] = { .nb64 = 100, .return_value = T_LINT, .name = "times", T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[101] = { .nb64 = 101, .return_value = T_LINT, .name = "ptrace", T_E_PTRACE_REQUEST, T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE },
		[102] = { .nb64 = 102, .return_value = T_UINT, .name = "getuid", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[103] = { .nb64 = 103, .return_value = T_INT, .name = "syslog", T_INT, T_STR, T_INT, T_NONE, T_NONE, T_NONE },
		[104] = { .nb64 = 104, .return_value = T_UINT, .name = "getgid", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[105] = { .nb64 = 105, .return_value = T_INT, .name = "setuid", T_UINT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[106] = { .nb64 = 106, .return_value = T_INT, .name = "setgid", T_UINT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[107] = { .nb64 = 107, .return_value = T_UINT, .name = "geteuid", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[108] = { .nb64 = 108, .return_value = T_UINT, .name = "getegid", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[109] = { .nb64 = 109, .return_value = T_INT, .name = "setpgid", T_INT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[110] = { .nb64 = 110, .return_value = T_INT, .name = "getppid", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[111] = { .nb64 = 111, .return_value = T_INT, .name = "getpgrp", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[112] = { .nb64 = 112, .return_value = T_INT, .name = "setsid", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[113] = { .nb64 = 113, .return_value = T_INT, .name = "setreuid", T_UINT, T_UINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[114] = { .nb64 = 114, .return_value = T_INT, .name = "setregid", T_UINT, T_UINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[115] = { .nb64 = 115, .return_value = T_INT, .name = "getgroups", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[116] = { .nb64 = 116, .return_value = T_INT, .name = "setgroups", T_ULINT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[117] = { .nb64 = 117, .return_value = T_INT, .name = "setresuid", T_UINT, T_UINT, T_UINT, T_NONE, T_NONE, T_NONE },
		[118] = { .nb64 = 118, .return_value = T_INT, .name = "getresuid", T_ADDR, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[119] = { .nb64 = 119, .return_value = T_INT, .name = "setresgid", T_UINT, T_UINT, T_UINT, T_NONE, T_NONE, T_NONE },
		[120] = { .nb64 = 120, .return_value = T_INT, .name = "getresgid", T_ADDR, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[121] = { .nb64 = 121, .return_value = T_INT, .name = "getpgid", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[122] = { .nb64 = 122, .return_value = T_INT, .name = "setfsuid", T_UINT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[123] = { .nb64 = 123, .return_value = T_INT, .name = "setfsgid", T_UINT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[124] = { .nb64 = 124, .return_value = T_INT, .name = "getsid", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[125] = { .nb64 = 125, .return_value = T_INT, .name = "capget", T_HEX, T_HEX, T_NONE, T_NONE, T_NONE, T_NONE },
		[126] = { .nb64 = 126, .return_value = T_INT, .name = "capset", T_HEX, T_HEX, T_NONE, T_NONE, T_NONE, T_NONE },
		[127] = { .nb64 = 127, .return_value = T_INT, .name = "rt_sigpending", T_ADDR, T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[128] = { .nb64 = 128, .return_value = T_INT, .name = "rt_sigtimedwait", T_ADDR, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[129] = { .nb64 = 129, .return_value = T_INT, .name = "rt_sigqueueinfo", T_INT, T_INT, T_ADDR, T_NONE, T_NONE, T_NONE },
		[130] = { .nb64 = 130, .return_value = T_INT, .name = "rt_sigsuspend", T_ADDR, T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[131] = { .nb64 = 131, .return_value = T_INT, .name = "sigaltstack", T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[132] = { .nb64 = 132, .return_value = T_INT, .name = "utime", T_STR, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[133] = { .nb64 = 133, .return_value = T_INT, .name = "mknod", T_STR, T_UINT, T_ULINT, T_NONE, T_NONE, T_NONE },
		[134] = { .nb64 = 134, .return_value = T_INT, .name = "uselib", T_STR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[135] = { .nb64 = 135, .return_value = T_INT, .name = "personality", T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[136] = { .nb64 = 136, .return_value = T_INT, .name = "ustat", T_ULINT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[137] = { .nb64 = 137, .return_value = T_INT, .name = "statfs", T_STR, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[138] = { .nb64 = 138, .return_value = T_INT, .name = "fstatfs", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[139] = { .nb64 = 139, .return_value = T_INT, .name = "sysfs", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[140] = { .nb64 = 140, .return_value = T_INT, .name = "getpriority", T_INT, T_UINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[141] = { .nb64 = 141, .return_value = T_INT, .name = "setpriority", T_INT, T_UINT, T_INT, T_NONE, T_NONE, T_NONE },
		[142] = { .nb64 = 142, .return_value = T_INT, .name = "sched_setparam", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[143] = { .nb64 = 143, .return_value = T_INT, .name = "sched_getparam", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[144] = { .nb64 = 144, .return_value = T_INT, .name = "sched_setscheduler", T_INT, T_INT, T_ADDR, T_NONE, T_NONE, T_NONE },
		[145] = { .nb64 = 145, .return_value = T_INT, .name = "sched_getscheduler", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[146] = { .nb64 = 146, .return_value = T_INT, .name = "sched_get_priority_max", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[147] = { .nb64 = 147, .return_value = T_INT, .name = "sched_get_priority_min", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[148] = { .nb64 = 148, .return_value = T_INT, .name = "sched_rr_get_interval", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[149] = { .nb64 = 149, .return_value = T_INT, .name = "mlock", T_ADDR, T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[150] = { .nb64 = 150, .return_value = T_INT, .name = "munlock", T_ADDR, T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[151] = { .nb64 = 151, .return_value = T_INT, .name = "mlockall", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[152] = { .nb64 = 152, .return_value = T_INT, .name = "munlockall", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[153] = { .nb64 = 153, .return_value = T_INT, .name = "vhangup", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[154] = { .nb64 = 154, .return_value = T_INT, .name = "modify_ldt", T_INT, T_ADDR, T_ULINT, T_NONE, T_NONE, T_NONE },
		[155] = { .nb64 = 155, .return_value = T_INT, .name = "pivot_root", T_STR, T_STR, T_NONE, T_NONE, T_NONE, T_NONE },
		[156] = { .nb64 = 156, .return_value = T_INT, .name = "_sysctl", T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[157] = { .nb64 = 157, .return_value = T_INT, .name = "prctl", T_INT, T_ULINT, T_ULINT, T_ULINT, T_ULINT, T_NONE },
		[158] = { .nb64 = 158, .return_value = T_INT, .name = "arch_prctl", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[159] = { .nb64 = 159, .return_value = T_INT, .name = "adjtimex", T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[160] = { .nb64 = 160, .return_value = T_INT, .name = "setrlimit", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[161] = { .nb64 = 161, .return_value = T_INT, .name = "chroot", T_STR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[162] = { .nb64 = 162, .return_value = T_NONE, .name = "sync", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[163] = { .nb64 = 163, .return_value = T_INT, .name = "acct", T_STR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[164] = { .nb64 = 164, .return_value = T_INT, .name = "settimeofday", T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[165] = { .nb64 = 165, .return_value = T_INT, .name = "mount", T_STR, T_STR, T_STR, T_ULINT, T_ADDR, T_NONE },
		[166] = { .nb64 = 166, .return_value = T_INT, .name = "umount2", T_STR, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[167] = { .nb64 = 167, .return_value = T_INT, .name = "swapon", T_STR, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[168] = { .nb64 = 168, .return_value = T_INT, .name = "swapoff", T_STR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[169] = { .nb64 = 169, .return_value = T_INT, .name = "reboot", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[170] = { .nb64 = 170, .return_value = T_INT, .name = "sethostname", T_STR, T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[171] = { .nb64 = 171, .return_value = T_INT, .name = "setdomainname", T_STR, T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[172] = { .nb64 = 172, .return_value = T_INT, .name = "iopl", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[173] = { .nb64 = 173, .return_value = T_INT, .name = "ioperm", T_ULINT, T_ULINT, T_INT, T_NONE, T_NONE, T_NONE },
		[174] = { .nb64 = 174, .return_value = T_CADDR_T, .name = "create_module", T_STR, T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[175] = { .nb64 = 175, .return_value = T_INT, .name = "init_module", T_ADDR, T_ULINT, T_STR, T_NONE, T_NONE, T_NONE },
		[176] = { .nb64 = 176, .return_value = T_INT, .name = "delete_module", T_STR, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[177] = { .nb64 = 177, .return_value = T_INT, .name = "get_kernel_syms", T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[178] = { .nb64 = 178, .return_value = T_INT, .name = "query_module", T_STR, T_INT, T_ADDR, T_ULINT, T_ADDR, T_NONE },
		[179] = { .nb64 = 179, .return_value = T_INT, .name = "quotactl", T_INT, T_STR, T_INT, T_CADDR_T, T_NONE, T_NONE },
		[180] = { .nb64 = 180, .return_value = T_LINT, .name = "nfsservctl", T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[181] = { .nb64 = 181, .return_value = T_LLINT, .name = "getpmsg", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[182] = { .nb64 = 182, .return_value = T_LLINT, .name = "putpmsg", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[183] = { .nb64 = 183, .return_value = T_LLINT, .name = "afs_syscall", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[184] = { .nb64 = 184, .return_value = T_LLINT, .name = "tuxcall", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[185] = { .nb64 = 185, .return_value = T_LLINT, .name = "security", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[186] = { .nb64 = 186, .return_value = T_INT, .name = "gettid", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[187] = { .nb64 = 187, .return_value = T_LINT, .name = "readahead", T_INT, T_LINT, T_ULINT, T_NONE, T_NONE, T_NONE },
		[188] = { .nb64 = 188, .return_value = T_INT, .name = "setxattr", T_STR, T_STR, T_ADDR, T_ULINT, T_INT, T_NONE },
		[189] = { .nb64 = 189, .return_value = T_INT, .name = "lsetxattr", T_STR, T_STR, T_ADDR, T_ULINT, T_INT, T_NONE },
		[190] = { .nb64 = 190, .return_value = T_INT, .name = "fsetxattr", T_INT, T_STR, T_ADDR, T_ULINT, T_INT, T_NONE },
		[191] = { .nb64 = 191, .return_value = T_LINT, .name = "getxattr", T_STR, T_STR, T_ADDR, T_ULINT, T_NONE, T_NONE },
		[192] = { .nb64 = 192, .return_value = T_LINT, .name = "lgetxattr", T_STR, T_STR, T_ADDR, T_ULINT, T_NONE, T_NONE },
		[193] = { .nb64 = 193, .return_value = T_LINT, .name = "fgetxattr", T_INT, T_STR, T_ADDR, T_ULINT, T_NONE, T_NONE },
		[194] = { .nb64 = 194, .return_value = T_LINT, .name = "listxattr", T_STR, T_STR, T_ULINT, T_NONE, T_NONE, T_NONE },
		[195] = { .nb64 = 195, .return_value = T_LINT, .name = "llistxattr", T_STR, T_STR, T_ULINT, T_NONE, T_NONE, T_NONE },
		[196] = { .nb64 = 196, .return_value = T_LINT, .name = "flistxattr", T_INT, T_STR, T_ULINT, T_NONE, T_NONE, T_NONE },
		[197] = { .nb64 = 197, .return_value = T_INT, .name = "removexattr", T_STR, T_STR, T_NONE, T_NONE, T_NONE, T_NONE },
		[198] = { .nb64 = 198, .return_value = T_INT, .name = "lremovexattr", T_STR, T_STR, T_NONE, T_NONE, T_NONE, T_NONE },
		[199] = { .nb64 = 199, .return_value = T_INT, .name = "fremovexattr", T_INT, T_STR, T_NONE, T_NONE, T_NONE, T_NONE },
		[200] = { .nb64 = 200, .return_value = T_INT, .name = "tkill", T_INT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[201] = { .nb64 = 201, .return_value = T_LINT, .name = "time", T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[202] = { .nb64 = 202, .return_value = T_INT, .name = "futex", T_ADDR, T_INT, T_INT, T_ADDR, T_ADDR, T_INT },
		[203] = { .nb64 = 203, .return_value = T_INT, .name = "sched_setaffinity", T_INT, T_ULINT, T_ADDR, T_NONE, T_NONE, T_NONE },
		[204] = { .nb64 = 204, .return_value = T_INT, .name = "sched_getaffinity", T_INT, T_ULINT, T_ADDR, T_NONE, T_NONE, T_NONE },
		[205] = { .nb64 = 205, .return_value = T_INT, .name = "set_thread_area", T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[206] = { .nb64 = 206, .return_value = T_INT, .name = "io_setup", T_UINT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[207] = { .nb64 = 207, .return_value = T_INT, .name = "io_destroy", T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[208] = { .nb64 = 208, .return_value = T_INT, .name = "io_getevents", T_ULINT, T_LINT, T_LINT, T_ADDR, T_ADDR, T_NONE },
		[209] = { .nb64 = 209, .return_value = T_INT, .name = "io_submit", T_ULINT, T_LINT, T_ADDR, T_NONE, T_NONE, T_NONE },
		[210] = { .nb64 = 210, .return_value = T_INT, .name = "io_cancel", T_ULINT, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[211] = { .nb64 = 211, .return_value = T_INT, .name = "get_thread_area", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[212] = { .nb64 = 212, .return_value = T_INT, .name = "lookup_dcookie", T_ULLINT, T_STR, T_ULINT, T_NONE, T_NONE, T_NONE },
		[213] = { .nb64 = 213, .return_value = T_INT, .name = "epoll_create", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[214] = { .nb64 = 214, .return_value = T_INT, .name = "epoll_ctl_old", T_HEX, T_HEX, T_HEX, T_ADDR, T_NONE, T_NONE },
		[215] = { .nb64 = 215, .return_value = T_INT, .name = "epoll_wait_old", T_HEX, T_ADDR, T_HEX, T_HEX, T_NONE, T_NONE },
		[216] = { .nb64 = 216, .return_value = T_INT, .name = "remap_file_pages", T_ADDR, T_ULINT, T_INT, T_ULINT, T_INT, T_NONE },
		[217] = { .nb64 = 217, .return_value = T_INT, .name = "getdents", T_UINT, T_ADDR, T_UINT, T_NONE, T_NONE, T_NONE },
		[218] = { .nb64 = 218, .return_value = T_LINT, .name = "set_tid_address", T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[219] = { .nb64 = 219, .return_value = T_INT, .name = "restart_syscall", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[220] = { .nb64 = 220, .return_value = T_INT, .name = "semtimedop", T_INT, T_ADDR, T_ULINT, T_ADDR, T_NONE, T_NONE },
		[221] = { .nb64 = 221, .return_value = T_INT, .name = "fadvise64", T_INT, T_LINT, T_LINT, T_HEX, T_NONE, T_NONE },
		[222] = { .nb64 = 222, .return_value = T_INT, .name = "timer_create", T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[223] = { .nb64 = 223, .return_value = T_INT, .name = "timer_settime", T_INT, T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE },
		[224] = { .nb64 = 224, .return_value = T_INT, .name = "timer_gettime", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[225] = { .nb64 = 225, .return_value = T_INT, .name = "timer_getoverrun", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[226] = { .nb64 = 226, .return_value = T_INT, .name = "timer_delete", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[227] = { .nb64 = 227, .return_value = T_INT, .name = "clock_settime", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[228] = { .nb64 = 228, .return_value = T_INT, .name = "clock_gettime", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[229] = { .nb64 = 229, .return_value = T_INT, .name = "clock_getres", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[230] = { .nb64 = 230, .return_value = T_INT, .name = "clock_nanosleep", T_INT, T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE },
		[231] = { .nb64 = 231, .return_value = T_NONE, .name = "exit_group", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[232] = { .nb64 = 232, .return_value = T_INT, .name = "epoll_wait", T_HEX, T_ADDR, T_HEX, T_HEX, T_NONE, T_NONE },
		[233] = { .nb64 = 233, .return_value = T_INT, .name = "epoll_ctl", T_HEX, T_HEX, T_HEX, T_ADDR, T_NONE, T_NONE },
		[234] = { .nb64 = 234, .return_value = T_INT, .name = "tgkill", T_INT, T_INT, T_INT, T_NONE, T_NONE, T_NONE },
		[235] = { .nb64 = 235, .return_value = T_INT, .name = "utimes", T_STR, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[236] = { .nb64 = 236, .return_value = T_LLINT, .name = "vserver", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[237] = { .nb64 = 237, .return_value = T_LINT, .name = "mbind", T_ADDR, T_ULINT, T_INT, T_ADDR, T_ULINT, T_UINT },
		[238] = { .nb64 = 238, .return_value = T_LINT, .name = "set_mempolicy", T_INT, T_ADDR, T_ULINT, T_NONE, T_NONE, T_NONE },
		[239] = { .nb64 = 239, .return_value = T_LINT, .name = "get_mempolicy", T_ADDR, T_ADDR, T_ULINT, T_ADDR, T_ULINT, T_NONE },
		[240] = { .nb64 = 240, .return_value = T_INT, .name = "mq_open", T_STR, T_INT, T_UINT, T_ADDR, T_NONE, T_NONE },
		[241] = { .nb64 = 241, .return_value = T_INT, .name = "mq_unlink", T_STR, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[242] = { .nb64 = 242, .return_value = T_INT, .name = "mq_timedsend", T_INT, T_STR, T_ULINT, T_UINT, T_ADDR, T_NONE },
		[243] = { .nb64 = 243, .return_value = T_LINT, .name = "mq_timedreceive", T_INT, T_STR, T_ULINT, T_ADDR, T_ADDR, T_NONE },
		[244] = { .nb64 = 244, .return_value = T_INT, .name = "mq_notify", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[245] = { .nb64 = 245, .return_value = T_INT, .name = "mq_getsetattr", T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[246] = { .nb64 = 246, .return_value = T_LINT, .name = "kexec_load", T_ULINT, T_ULINT, T_ADDR, T_ULINT, T_NONE, T_NONE },
		[247] = { .nb64 = 247, .return_value = T_INT, .name = "waitid", T_UINT, T_UINT, T_ADDR, T_INT, T_NONE, T_NONE },
		[248] = { .nb64 = 248, .return_value = T_INT, .name = "add_key", T_STR, T_STR, T_ADDR, T_ULINT, T_INT, T_NONE },
		[249] = { .nb64 = 249, .return_value = T_INT, .name = "request_key", T_STR, T_STR, T_STR, T_INT, T_NONE, T_NONE },
		[250] = { .nb64 = 250, .return_value = T_LINT, .name = "keyctl", T_HEX, T_HEX, T_HEX, T_HEX, T_HEX, T_NONE },
		[251] = { .nb64 = 251, .return_value = T_INT, .name = "ioprio_set", T_INT, T_INT, T_INT, T_NONE, T_NONE, T_NONE },
		[252] = { .nb64 = 252, .return_value = T_INT, .name = "ioprio_get", T_INT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[253] = { .nb64 = 253, .return_value = T_INT, .name = "inotify_init", T_NONE, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[254] = { .nb64 = 254, .return_value = T_INT, .name = "inotify_add_watch", T_INT, T_STR, T_UINT, T_NONE, T_NONE, T_NONE },
		[255] = { .nb64 = 255, .return_value = T_INT, .name = "inotify_rm_watch", T_INT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[256] = { .nb64 = 256, .return_value = T_LINT, .name = "migrate_pages", T_INT, T_ULINT, T_ADDR, T_ADDR, T_NONE, T_NONE },
		[257] = { .nb64 = 257, .return_value = T_INT, .name = "openat", T_INT, T_STR, T_INT, T_UINT, T_NONE, T_NONE },
		[258] = { .nb64 = 258, .return_value = T_INT, .name = "mkdirat", T_INT, T_STR, T_UINT, T_NONE, T_NONE, T_NONE },
		[259] = { .nb64 = 259, .return_value = T_INT, .name = "mknodat", T_INT, T_STR, T_UINT, T_ULINT, T_NONE, T_NONE },
		[260] = { .nb64 = 260, .return_value = T_INT, .name = "fchownat", T_INT, T_STR, T_UINT, T_UINT, T_INT, T_NONE },
		[261] = { .nb64 = 261, .return_value = T_INT, .name = "futimesat", T_INT, T_STR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[262] = { .nb64 = 262, .return_value = T_INT, .name = "newfstatat", T_INT, T_ADDR, T_ADDR, T_INT, T_NONE, T_NONE },
		[263] = { .nb64 = 263, .return_value = T_INT, .name = "unlinkat", T_INT, T_STR, T_INT, T_NONE, T_NONE, T_NONE },
		[264] = { .nb64 = 264, .return_value = T_INT, .name = "renameat", T_INT, T_STR, T_INT, T_STR, T_NONE, T_NONE },
		[265] = { .nb64 = 265, .return_value = T_INT, .name = "linkat", T_INT, T_STR, T_INT, T_STR, T_INT, T_NONE },
		[266] = { .nb64 = 266, .return_value = T_INT, .name = "symlinkat", T_STR, T_INT, T_STR, T_NONE, T_NONE, T_NONE },
		[267] = { .nb64 = 267, .return_value = T_LINT, .name = "readlinkat", T_INT, T_STR, T_STR, T_ULINT, T_NONE, T_NONE },
		[268] = { .nb64 = 268, .return_value = T_INT, .name = "fchmodat", T_INT, T_STR, T_UINT, T_INT, T_NONE, T_NONE },
		[269] = { .nb64 = 269, .return_value = T_INT, .name = "faccessat", T_INT, T_STR, T_INT, T_INT, T_NONE, T_NONE },
		[270] = { .nb64 = 270, .return_value = T_INT, .name = "pselect6", T_INT, T_ADDR, T_ADDR, T_ADDR, T_ADDR, T_ADDR },
		[271] = { .nb64 = 271, .return_value = T_INT, .name = "ppoll", T_ADDR, T_ULINT, T_ADDR, T_ADDR, T_NONE, T_NONE },
		[272] = { .nb64 = 272, .return_value = T_INT, .name = "unshare", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[273] = { .nb64 = 273, .return_value = T_LINT, .name = "set_robust_list", T_ADDR, T_ULINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[274] = { .nb64 = 274, .return_value = T_LINT, .name = "get_robust_list", T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[275] = { .nb64 = 275, .return_value = T_LINT, .name = "splice", T_INT, T_ADDR, T_INT, T_ADDR, T_ULINT, T_UINT },
		[276] = { .nb64 = 276, .return_value = T_LINT, .name = "tee", T_INT, T_INT, T_ULINT, T_UINT, T_NONE, T_NONE },
		[277] = { .nb64 = 277, .return_value = T_INT, .name = "sync_file_range", T_INT, T_LINT, T_LINT, T_UINT, T_NONE, T_NONE },
		[278] = { .nb64 = 278, .return_value = T_LINT, .name = "vmsplice", T_INT, T_ADDR, T_ULINT, T_UINT, T_NONE, T_NONE },
		[279] = { .nb64 = 279, .return_value = T_LINT, .name = "move_pages", T_INT, T_ULINT, T_ADDR, T_ADDR, T_ADDR, T_INT },
		[280] = { .nb64 = 280, .return_value = T_INT, .name = "utimensat", T_INT, T_STR, T_ADDR, T_INT, T_NONE, T_NONE },
		[281] = { .nb64 = 281, .return_value = T_INT, .name = "epoll_pwait", T_INT, T_ADDR, T_INT, T_INT, T_ADDR, T_NONE },
		[282] = { .nb64 = 282, .return_value = T_INT, .name = "signalfd", T_INT, T_ADDR, T_INT, T_NONE, T_NONE, T_NONE },
		[283] = { .nb64 = 283, .return_value = T_INT, .name = "timerfd_create", T_INT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[284] = { .nb64 = 284, .return_value = T_INT, .name = "eventfd", T_UINT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[285] = { .nb64 = 285, .return_value = T_INT, .name = "fallocate", T_INT, T_INT, T_LINT, T_LINT, T_NONE, T_NONE },
		[286] = { .nb64 = 286, .return_value = T_INT, .name = "timerfd_settime", T_INT, T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE },
		[287] = { .nb64 = 287, .return_value = T_INT, .name = "timerfd_gettime", T_INT, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[288] = { .nb64 = 288, .return_value = T_INT, .name = "accept4", T_INT, T_ADDR, T_ADDR, T_INT, T_NONE, T_NONE },
		[289] = { .nb64 = 289, .return_value = T_INT, .name = "signalfd4", T_INT, T_ADDR, T_INT, T_NONE, T_NONE, T_NONE },
		[290] = { .nb64 = 290, .return_value = T_INT, .name = "eventfd2", T_UINT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[291] = { .nb64 = 291, .return_value = T_INT, .name = "epoll_create1", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[292] = { .nb64 = 292, .return_value = T_INT, .name = "dup3", T_INT, T_INT, T_INT, T_NONE, T_NONE, T_NONE },
		[293] = { .nb64 = 293, .return_value = T_INT, .name = "pipe2", T_ADDR, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[294] = { .nb64 = 294, .return_value = T_INT, .name = "inotify_init1", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[295] = { .nb64 = 295, .return_value = T_LINT, .name = "preadv", T_INT, T_ADDR, T_INT, T_LINT, T_NONE, T_NONE },
		[296] = { .nb64 = 296, .return_value = T_LINT, .name = "pwritev", T_INT, T_ADDR, T_INT, T_LINT, T_NONE, T_NONE },
		[297] = { .nb64 = 297, .return_value = T_INT, .name = "rt_tgsigqueueinfo", T_INT, T_INT, T_INT, T_ADDR, T_NONE, T_NONE },
		[298] = { .nb64 = 298, .return_value = T_INT, .name = "perf_event_open", T_ADDR, T_INT, T_INT, T_INT, T_ULINT, T_NONE },
		[299] = { .nb64 = 299, .return_value = T_INT, .name = "recvmmsg", T_INT, T_ADDR, T_UINT, T_INT, T_ADDR, T_NONE },
		[300] = { .nb64 = 300, .return_value = T_INT, .name = "fanotify_init", T_UINT, T_UINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[301] = { .nb64 = 301, .return_value = T_INT, .name = "fanotify_mark", T_INT, T_UINT, T_ULINT, T_INT, T_STR, T_NONE },
		[302] = { .nb64 = 302, .return_value = T_INT, .name = "prlimit", T_INT, T_INT, T_ADDR, T_ADDR, T_NONE, T_NONE },
		[303] = { .nb64 = 303, .return_value = T_INT, .name = "name_to_handle_at", T_INT, T_STR, T_ADDR, T_ADDR, T_INT, T_NONE },
		[304] = { .nb64 = 304, .return_value = T_INT, .name = "open_by_handle_at", T_INT, T_ADDR, T_INT, T_NONE, T_NONE, T_NONE },
		[305] = { .nb64 = 305, .return_value = T_INT, .name = "clock_adjtime", T_HEX, T_ADDR, T_NONE, T_NONE, T_NONE, T_NONE },
		[306] = { .nb64 = 306, .return_value = T_INT, .name = "syncfs", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[307] = { .nb64 = 307, .return_value = T_INT, .name = "sendmmsg", T_INT, T_ADDR, T_UINT, T_INT, T_NONE, T_NONE },
		[308] = { .nb64 = 308, .return_value = T_INT, .name = "setns", T_INT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[309] = { .nb64 = 309, .return_value = T_INT, .name = "getcpu", T_ADDR, T_ADDR, T_ADDR, T_NONE, T_NONE, T_NONE },
		[310] = { .nb64 = 310, .return_value = T_LINT, .name = "process_vm_readv", T_INT, T_ADDR, T_ULINT, T_ADDR, T_ULINT, T_ULINT },
		[311] = { .nb64 = 311, .return_value = T_LINT, .name = "process_vm_writev", T_INT, T_ADDR, T_ULINT, T_ADDR, T_ULINT, T_ULINT },
		[312] = { .nb64 = 312, .return_value = T_INT, .name = "kcmp", T_INT, T_INT, T_INT, T_ULINT, T_ULINT, T_NONE },
		[313] = { .nb64 = 313, .return_value = T_INT, .name = "finit_module", T_INT, T_STR, T_INT, T_NONE, T_NONE, T_NONE },
		[314] = { .nb64 = 314, .return_value = T_INT, .name = "sched_setattr", T_INT, T_ADDR, T_UINT, T_NONE, T_NONE, T_NONE },
		[315] = { .nb64 = 315, .return_value = T_INT, .name = "sched_getattr", T_INT, T_ADDR, T_UINT, T_UINT, T_NONE, T_NONE },
		[316] = { .nb64 = 316, .return_value = T_INT, .name = "renameat2", T_INT, T_STR, T_INT, T_STR, T_UINT, T_NONE },
		[317] = { .nb64 = 317, .return_value = T_INT, .name = "seccomp", T_UINT, T_UINT, T_ADDR, T_NONE, T_NONE, T_NONE },
		[318] = { .nb64 = 318, .return_value = T_LINT, .name = "getrandom", T_ADDR, T_ULINT, T_UINT, T_NONE, T_NONE, T_NONE },
		[319] = { .nb64 = 319, .return_value = T_INT, .name = "memfd_create", T_STR, T_UINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[320] = { .nb64 = 320, .return_value = T_LINT, .name = "kexec_file_load", T_INT, T_INT, T_ULINT, T_STR, T_ULINT, T_NONE },
		[321] = { .nb64 = 321, .return_value = T_INT, .name = "bpf", T_INT, T_ADDR, T_UINT, T_NONE, T_NONE, T_NONE },
		[322] = { .nb64 = 322, .return_value = T_INT, .name = "execveat", T_INT, T_STR, T_ADDR, T_ADDR, T_INT, T_NONE },
		[323] = { .nb64 = 323, .return_value = T_INT, .name = "userfaultfd", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[324] = { .nb64 = 324, .return_value = T_INT, .name = "membarrier", T_INT, T_INT, T_NONE, T_NONE, T_NONE, T_NONE },
		[325] = { .nb64 = 325, .return_value = T_INT, .name = "mlock2", T_ADDR, T_ULINT, T_INT, T_NONE, T_NONE, T_NONE },
		[326] = { .nb64 = 326, .return_value = T_LINT, .name = "copy_file_range", T_INT, T_ADDR, T_INT, T_ADDR, T_ULINT, T_UINT },
		[327] = { .nb64 = 327, .return_value = T_LINT, .name = "preadv2", T_INT, T_ADDR, T_INT, T_LINT, T_INT, T_NONE },
		[328] = { .nb64 = 328, .return_value = T_LINT, .name = "pwritev2", T_INT, T_ADDR, T_INT, T_LINT, T_INT, T_NONE },
		[329] = { .nb64 = 329, .return_value = T_INT, .name = "pkey_mprotect", T_ADDR, T_ULINT, T_INT, T_INT, T_NONE, T_NONE },
		[330] = { .nb64 = 330, .return_value = T_INT, .name = "pkey_alloc", T_UINT, T_UINT, T_NONE, T_NONE, T_NONE, T_NONE },
		[331] = { .nb64 = 331, .return_value = T_INT, .name = "pkey_free", T_INT, T_NONE, T_NONE, T_NONE, T_NONE, T_NONE },
		[332] = { .nb64 = 332, .return_value = T_INT, .name = "statx", T_INT, T_STR, T_INT, T_UINT, T_ADDR, T_NONE },
		[333] = { .nb64 = 333, .return_value = T_INT, .name = "io_pgetevents", T_ULINT, T_LINT, T_LINT, T_ADDR, T_ADDR, T_NONE },
		[334] = { .nb64 = 334, .return_value = T_INT, .name = "rseq", T_ADDR, T_HEX, T_HEX, T_HEX, T_NONE, T_NONE },
};
